#image : mcr.microsoft.com/dotnet/framework/sdk:4.8
#image: mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019

stages:
  - build
  - test

before_script:
    - cd WpfApp2

build_App:
  stage: build
  tags:
   - Docker 
   - FB2
   - Windows 
   - Runner 
  script:
   - nuget.exe restore "WpfApp2.sln"
   - MSBuild.exe "WpfApp2.sln" -t:Build -p:Configuration=Release /p:Platform="Any CPU" /clp:ErrorsOnly
  artifacts:
    expire_in: 7 days
    paths:
      - .\WpfApp2\WpfApp2\bin\Release
      - .\WpfApp2\UnitTestProject\bin\Release


test_App:
  stage: test
  tags:
   - Docker 
   - FB2
   - Windows 
   - Runner 
  script:
   - cd .\UnitTestProject\bin\Release
   - vstest.console UnitTestProject.dll /logger:trx

  artifacts:
    when: always
    paths:
      - .\WpfApp2\UnitTestProject\bin\Release\TestResults

